"""First-run wizard — 모의/실거래 모드 선택 + API 키 입력 (Tkinter, 의존성 0).

Usage:
  python scripts/setup_wizard.py
"""

from __future__ import annotations

import os
import re
import tkinter as tk
from pathlib import Path
from tkinter import messagebox, ttk


ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / ".env"
EXAMPLE_PATH = ROOT / "release" / ".env.example"


def load_existing_env() -> dict:
    out = {}
    if not ENV_PATH.exists():
        return out
    for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if "=" in line:
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def save_env(values: dict):
    template = EXAMPLE_PATH.read_text(encoding="utf-8") if EXAMPLE_PATH.exists() else ""
    if template:
        for key, val in values.items():
            pattern = re.compile(rf"^{re.escape(key)}=.*$", re.MULTILINE)
            if pattern.search(template):
                template = pattern.sub(f"{key}={val}", template)
            else:
                template += f"\n{key}={val}"
        ENV_PATH.write_text(template, encoding="utf-8")
    else:
        lines = ["# Auto-generated by setup_wizard.py"]
        for key, val in values.items():
            lines.append(f"{key}={val}")
        ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    existing = load_existing_env()

    root = tk.Tk()
    root.title("자동매매 시스템 — 설정 Wizard")
    root.geometry("720x820")

    # Header
    header = tk.Frame(root, bg="#2c5aa0")
    header.pack(fill="x")
    tk.Label(header, text="🔑 자동매매 시스템 설정",
              bg="#2c5aa0", fg="white",
              font=("맑은 고딕", 14, "bold")).pack(pady=(12, 2))
    tk.Label(header, text="모드 선택 + API 키 입력",
              bg="#2c5aa0", fg="#cce0ff",
              font=("맑은 고딕", 9)).pack(pady=(0, 12))

    # Scrollable
    canvas = tk.Canvas(root, highlightthickness=0)
    sb = ttk.Scrollbar(root, orient="vertical", command=canvas.yview)
    inner = tk.Frame(canvas)
    inner.bind("<Configure>",
                lambda e: canvas.configure(scrollregion=canvas.bbox("all")))
    canvas.create_window((0, 0), window=inner, anchor="nw")
    canvas.configure(yscrollcommand=sb.set)
    canvas.pack(side="left", fill="both", expand=True, padx=20, pady=10)
    sb.pack(side="right", fill="y")

    def _on_wheel(event):
        canvas.yview_scroll(int(-event.delta / 120), "units")
    canvas.bind_all("<MouseWheel>", _on_wheel)

    # ═══════════════════════════════════════════════════════════
    # KIS 섹션
    # ═══════════════════════════════════════════════════════════
    kis_frame = tk.LabelFrame(inner, text="📈 KIS 한국 주식",
                                padx=14, pady=10, font=("맑은 고딕", 10, "bold"))
    kis_frame.pack(fill="x", pady=(0, 14))

    # KIS 모드 선택
    tk.Label(kis_frame, text="모드:",
              font=("맑은 고딕", 9, "bold")).grid(row=0, column=0, sticky="w", pady=4)
    kis_env_var = tk.StringVar(value=existing.get("KIS_ENV", "vts"))
    kis_env_frame = tk.Frame(kis_frame)
    kis_env_frame.grid(row=0, column=1, sticky="w", padx=8)
    tk.Radiobutton(kis_env_frame, text="🟢 모의투자 (vts, 가짜 자금)",
                    variable=kis_env_var, value="vts",
                    font=("맑은 고딕", 9)).pack(anchor="w")
    tk.Radiobutton(kis_env_frame, text="🔴 실거래 (prod, 진짜 돈)",
                    variable=kis_env_var, value="prod", fg="#c0392b",
                    font=("맑은 고딕", 9, "bold")).pack(anchor="w")

    # KIS 키
    kis_entries = {}
    for i, (key, label) in enumerate([
        ("KIS_APP_KEY", "APP Key"),
        ("KIS_APP_SECRET", "APP Secret"),
        ("KIS_ACCOUNT", "계좌 (8자리)"),
    ], start=1):
        tk.Label(kis_frame, text=label, anchor="w",
                 font=("맑은 고딕", 9)).grid(row=i, column=0, sticky="w", pady=3)
        e = tk.Entry(kis_frame, width=58, font=("Consolas", 9), show="•")
        if existing.get(key):
            e.insert(0, existing[key])
        e.grid(row=i, column=1, sticky="w", padx=8, pady=3)
        kis_entries[key] = e

    # KIS DRY_RUN
    tk.Label(kis_frame, text="DRY_RUN", anchor="w",
              font=("맑은 고딕", 9)).grid(row=4, column=0, sticky="w", pady=3)
    kis_dry_var = tk.BooleanVar(value=existing.get("KIS_DRY_RUN", "false").lower() == "true")
    tk.Checkbutton(kis_frame, text="실주문 안 함 (시그널만 로깅)",
                    variable=kis_dry_var, font=("맑은 고딕", 9)).grid(row=4, column=1, sticky="w")

    # ═══════════════════════════════════════════════════════════
    # Binance 섹션
    # ═══════════════════════════════════════════════════════════
    bnc_frame = tk.LabelFrame(inner, text="🪙 Binance 코인",
                                padx=14, pady=10, font=("맑은 고딕", 10, "bold"))
    bnc_frame.pack(fill="x", pady=(0, 14))

    # Binance 모드
    tk.Label(bnc_frame, text="모드:",
              font=("맑은 고딕", 9, "bold")).grid(row=0, column=0, sticky="w", pady=4)
    bnc_env_var = tk.StringVar(value=existing.get("BINANCE_ENV", "testnet"))
    bnc_env_frame = tk.Frame(bnc_frame)
    bnc_env_frame.grid(row=0, column=1, sticky="w", padx=8)
    tk.Radiobutton(bnc_env_frame, text="🟢 Testnet (가짜 USDT)",
                    variable=bnc_env_var, value="testnet",
                    font=("맑은 고딕", 9)).pack(anchor="w")
    tk.Radiobutton(bnc_env_frame, text="🔴 Mainnet (진짜 돈)",
                    variable=bnc_env_var, value="mainnet", fg="#c0392b",
                    font=("맑은 고딕", 9, "bold")).pack(anchor="w")

    # Binance 키 — testnet + mainnet 둘 다 입력 가능
    bnc_entries = {}
    for i, (key, label) in enumerate([
        ("BINANCE_TESTNET_API_KEY", "Testnet Key"),
        ("BINANCE_TESTNET_API_SECRET", "Testnet Secret"),
        ("BINANCE_API_KEY", "Mainnet Key (실거래용)"),
        ("BINANCE_API_SECRET", "Mainnet Secret (실거래용)"),
    ], start=1):
        is_mainnet = "TESTNET" not in key
        fg = "#c0392b" if is_mainnet else "#444"
        tk.Label(bnc_frame, text=label, anchor="w", fg=fg,
                 font=("맑은 고딕", 9, "bold" if is_mainnet else "normal")).grid(
            row=i, column=0, sticky="w", pady=3)
        e = tk.Entry(bnc_frame, width=58, font=("Consolas", 9), show="•")
        if existing.get(key):
            e.insert(0, existing[key])
        e.grid(row=i, column=1, sticky="w", padx=8, pady=3)
        bnc_entries[key] = e

    # Binance DRY_RUN
    tk.Label(bnc_frame, text="DRY_RUN", anchor="w",
              font=("맑은 고딕", 9)).grid(row=5, column=0, sticky="w", pady=3)
    bnc_dry_var = tk.BooleanVar(value=existing.get("BINANCE_DRY_RUN", "false").lower() == "true")
    tk.Checkbutton(bnc_frame, text="실주문 안 함",
                    variable=bnc_dry_var, font=("맑은 고딕", 9)).grid(row=5, column=1, sticky="w")

    # ═══════════════════════════════════════════════════════════
    # 도움말
    # ═══════════════════════════════════════════════════════════
    help_frame = tk.LabelFrame(inner, text="📖 발급 방법",
                                 padx=12, pady=8, font=("맑은 고딕", 9))
    help_frame.pack(fill="x", pady=(0, 14))
    tk.Label(help_frame, text="• KIS 모의투자: https://apiportal.koreainvestment.com → 회원가입 → 모의투자 신청",
              font=("맑은 고딕", 8), fg="#0066cc", anchor="w").pack(fill="x")
    tk.Label(help_frame, text="• KIS 실거래:   같은 사이트 → 실전투자 신청 (별도 키)",
              font=("맑은 고딕", 8), fg="#0066cc", anchor="w").pack(fill="x")
    tk.Label(help_frame, text="• Binance Testnet: https://testnet.binancefuture.com → 이메일 가입",
              font=("맑은 고딕", 8), fg="#0066cc", anchor="w").pack(fill="x")
    tk.Label(help_frame, text="• Binance Mainnet: https://www.binance.com → API Management (실거래!)",
              font=("맑은 고딕", 8), fg="#0066cc", anchor="w").pack(fill="x")

    # ═══════════════════════════════════════════════════════════
    # 저장 / 취소 버튼
    # ═══════════════════════════════════════════════════════════
    footer = tk.Frame(root, bg="#f4f4f4", pady=10)
    footer.pack(fill="x", side="bottom")

    def show_live_warning(env_label: str) -> bool:
        return messagebox.askyesno(
            f"⚠️ 실거래 확인 — {env_label}",
            f"{env_label} 모드는 진짜 돈으로 매매합니다.\n\n"
            "확인 사항:\n"
            "• Backtest 결과 ≠ 실제 수익 보장 X\n"
            "• Slippage / 수수료 / 세금 발생\n"
            "• 작은 자본부터 시작 권장\n"
            "• 매일 점검 권장\n"
            "• Stop-loss 자동 적용 안 됨 (signal-based exit 만)\n\n"
            "정말 실거래로 설정하시겠습니까?",
            icon="warning",
        )

    def on_save():
        kis_env = kis_env_var.get()
        bnc_env = bnc_env_var.get()

        # 실거래 경고
        if kis_env == "prod":
            if not show_live_warning("KIS 실거래"):
                return
        if bnc_env == "mainnet":
            if not show_live_warning("Binance Mainnet"):
                return

        # 필수 검증 (현재 모드 키만)
        missing = []
        if not kis_entries["KIS_APP_KEY"].get().strip():
            missing.append("KIS APP Key")
        if not kis_entries["KIS_APP_SECRET"].get().strip():
            missing.append("KIS APP Secret")
        if not kis_entries["KIS_ACCOUNT"].get().strip():
            missing.append("KIS 계좌")

        if bnc_env == "testnet":
            if not bnc_entries["BINANCE_TESTNET_API_KEY"].get().strip():
                missing.append("Binance Testnet Key")
        elif bnc_env == "mainnet":
            if not bnc_entries["BINANCE_API_KEY"].get().strip():
                missing.append("Binance Mainnet Key")

        if missing:
            messagebox.showerror("필수 항목 누락",
                "다음 항목 입력 필요:\n\n• " + "\n• ".join(missing))
            return

        # Save
        values = {
            "KIS_ENV": kis_env,
            "KIS_DRY_RUN": "true" if kis_dry_var.get() else "false",
            "KIS_ACCOUNT_PROD": "01",
            "BINANCE_ENV": bnc_env,
            "BINANCE_DRY_RUN": "true" if bnc_dry_var.get() else "false",
        }
        for key, e in {**kis_entries, **bnc_entries}.items():
            v = e.get().strip()
            if v:
                values[key] = v

        try:
            save_env(values)
            mode_msg = []
            if kis_env == "prod":
                mode_msg.append("⚠️ KIS = 실거래")
            else:
                mode_msg.append("✓ KIS = 모의투자")
            if bnc_env == "mainnet":
                mode_msg.append("⚠️ Binance = 실거래")
            else:
                mode_msg.append("✓ Binance = Testnet")

            messagebox.showinfo(
                "저장 완료",
                f".env 저장됨:\n{ENV_PATH}\n\n"
                + "\n".join(mode_msg)
                + "\n\n이제 Launcher 에서 실행 가능."
            )
            root.destroy()
        except Exception as e:
            messagebox.showerror("저장 실패", str(e))

    def on_cancel():
        root.destroy()

    tk.Button(footer, text="저장", command=on_save,
              bg="#0b8043", fg="white", font=("맑은 고딕", 10, "bold"),
              width=12, pady=4).pack(side="right", padx=10)
    tk.Button(footer, text="취소", command=on_cancel,
              bg="#888", fg="white", font=("맑은 고딕", 10),
              width=12, pady=4).pack(side="right")

    root.mainloop()


if __name__ == "__main__":
    main()
